### ISSUE TITLE
Add proxy-awareness mechanism to the spring boot apps

### ISSUE THREAD

**Issue by sgroh** [sdhealthconnect/leap-demos#36]
Tests alternatives like
```
server:
  port: 9092
  use-forwarded-headers: true
```
or 
```
server:
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
```
